import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Textbook sidebar following the Physical AI & Humanoid Robotics structure
  textbookSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'module-1/intro'},
      items: [
        {
          type: 'category',
          label: 'Part 1-1: ROS 2 Basics',
          link: {type: 'doc', id: 'module-1/part-1-1/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 1-1-1: Introduction to ROS 2',
              link: {type: 'doc', id: 'module-1/part-1-1/chapter-1-1-1/intro'},
              items: [
                'module-1/part-1-1/chapter-1-1-1/lesson-1',
                'module-1/part-1-1/chapter-1-1-1/lesson-2',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {type: 'doc', id: 'module-2/intro'},
      items: [
        {
          type: 'category',
          label: 'Part 2-1: Gazebo Simulation',
          link: {type: 'doc', id: 'module-2/part-2-1/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 2-1-1: Gazebo Physics Simulation',
              link: {type: 'doc', id: 'module-2/part-2-1/chapter-2-1-1/intro'},
              items: [
                'module-2/part-2-1/chapter-2-1-1/lesson-1',
                'module-2/part-2-1/chapter-2-1-1/lesson-2',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 2-2: Unity Environment',
          link: {type: 'doc', id: 'module-2/part-2-2/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 2-2-1: Unity for Human-Robot Interaction',
              link: {type: 'doc', id: 'module-2/part-2-2/chapter-2-2-1/intro'},
              items: [
                'module-2/part-2-2/chapter-2-2-1/lesson-1',
                'module-2/part-2-2/chapter-2-2-1/lesson-2',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      link: {type: 'doc', id: 'module-3/intro'},
      items: [
        {
          type: 'category',
          label: 'Part 3-1: NVIDIA Isaac Sim',
          link: {type: 'doc', id: 'module-3/part-3-1/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 3-1-1: Photorealistic Simulation',
              link: {type: 'doc', id: 'module-3/part-3-1/chapter-3-1-1/intro'},
              items: [
                'module-3/part-3-1/chapter-3-1-1/lesson-1',
                'module-3/part-3-1/chapter-3-1-1/lesson-2',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Part 3-2: Isaac ROS',
          link: {type: 'doc', id: 'module-3/part-3-2/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 3-2-1: VSLAM Implementation',
              link: {type: 'doc', id: 'module-3/part-3-2/chapter-3-2-1/intro'},
              items: [
                'module-3/part-3-2/chapter-3-2-1/lesson-1',
                'module-3/part-3-2/chapter-3-2-1/lesson-2',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {type: 'doc', id: 'module-4/intro'},
      items: [
        {
          type: 'category',
          label: 'Part 4-1: Voice-to-Action Systems',
          link: {type: 'doc', id: 'module-4/part-4-1/intro'},
          items: [
            {
              type: 'category',
              label: 'Chapter 4-1-1: OpenAI Whisper Implementation',
              link: {type: 'doc', id: 'module-4/part-4-1/chapter-4-1-1/intro'},
              items: [
                'module-4/part-4-1/chapter-4-1-1/lesson-1',
                'module-4/part-4-1/chapter-4-1-1/lesson-2',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
